#version: '3'

services:
  school_api_server:
    container_name: school_api_server
    build: .
    restart: always
    environment:
      - TZ=Europe/Moscow
      - PYTHONUNBUFFERED=1
      - DATABASE_HOSTNAME=school_api_db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=api_password
      - DATABASE_NAME=api_db
      - DATABASE_USERNAME=api_user
      - SECRET_KEY=01c467dd1e55dc862fcbc0be6cc7393abd4af5e29c12f182737fb3e449ebbedc
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    volumes:
      - ./:/app
      - ./logs:/logs
    working_dir: /app
    depends_on:
      - school_api_db
    ports:
      - '40000:4000'
    command: uvicorn app.main:app --host 0.0.0.0 --port 4000 --reload

  school_api_db:
    image: postgres:latest
    container_name: school_api_db_name
    restart: always
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: api_password
      POSTGRES_DB: api_db
    ports:
      - '4444:5432'
    # volumes:
      # - postgres-db:/var/lib/postgresql/data

# volumes:
  # postgres-db:

# End of docker-compose.yml